# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DefPointValidator
                                 A QGIS plugin
 This pugling takes def point ans validate it using planet month mosiac tiles.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-09-28
        copyright            : (C) 2019 by ga.becerra10, hc.torres , my.castro10, rj.santacruz @uniandes.edu.co;   ggalindo@ideam.gov.co
        email                : gusbeca@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DefPointValidator class from file DefPointValidator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .def_point_val import DefPointValidator
    return DefPointValidator(iface)
